/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "timer.h"  /* Include header file for LED and GPIO functions */
#include "i2c.h"
#include "ssd1306.h"
#include "fonts.h"
/* SysTick handler function
 * This function is called every time the SysTick timer overflows (typically every 1 ms)
 */
void SysTick_Handler(void) {
    system_time++; // Increment every SysTick interrupt (typically every 1 ms)
}


int main(void)
{
	/* You can use the Command Shell Console in STM32CubeIDE or an
	 * external program such as Putty or TeraTerm to view printf output.
	 * The settings are: Baud: 9600, Parity: None, Stop Bits: 1 with
	 * the ST-Link COM port setting.
	 * Clocks: Processor = 48 Mhz. AHB = 48 MHz. APB = 24 MHz.
	 */

	/* Initialize GPIO pins for LEDs, Systick Timer and switch */
	init_gpio();    /* Configures general-purpose I/O pins */
	init_timer();   /* Configures and starts the hardware timer (e.g., TIM3) */
	init_i2c();
	//init_timer3();
	//init_systick();
	/* Main program loop
     * The state machine function manages the system states (e.g., LED control)
     */
	SSD1306_Init();
	SSD1306_GotoXY(0,0);


    // Display a digit or number
    char number[10];
    int digit = 1234;  // Example number
     sprintf(number, "%d", digit);  // Convert the number to a string
    SSD1306_Puts(number, &Font_7x10, SSD1306_COLOR_WHITE);


	//SSD1306_Puts("Hello",&Font_7x10,SSD1306_COLOR_WHITE);
	SSD1306_UpdateScreen();
	printf(" Starting main loop \r \n");
   // uint8_t who_am_i = 0;
  //  I2C_ReadMultiple(SLAVE_ADDRESS_LCD, MPU6050_WHO_AM_I, &who_am_i, 1);
   // delayuS(50000);
   // lcd_send_command(0x30);
	//I2C_Scan();
    while (1) {

    	trig_func();

     	  sprintf(number, "%ld", distance);  // Convert the number to a string
     	    SSD1306_Fill(SSD1306_COLOR_BLACK);
     		SSD1306_GotoXY(0,0);

      	  SSD1306_Puts(number, &Font_7x10, SSD1306_COLOR_WHITE);
      	SSD1306_UpdateScreen();

   }

}
